import { type Component, createSignal, Show } from 'solid-js';
import {
  AppShell,
  BrandSelector,
  OutputPreview,
  RecipePicker,
  SourceInput,
  StreamViewer,
} from './components';
import type { BrandProfile, GeneratedContent, Recipe, SourceDoc } from './types';

type Step = 'input' | 'recipe' | 'voice' | 'generate' | 'output';

const App: Component = () => {
  const [step, setStep] = createSignal<Step>('input');
  const [selectedRecipe, setSelectedRecipe] = createSignal<Recipe | null>(null);
  const [selectedBrandId, setSelectedBrandId] = createSignal<string | null>(null);
  const [isStreaming, setIsStreaming] = createSignal(false);
  const [streamContent, setStreamContent] = createSignal('');
  const [generatedContent, setGeneratedContent] = createSignal<GeneratedContent | null>(null);

  const handleSourceSubmit = (_doc: SourceDoc) => {
    setStep('recipe');
  };

  const handleRecipeSelect = (recipe: Recipe) => {
    setSelectedRecipe(recipe);
    setStep('voice');
  };

  const handleBrandSelect = (profile: BrandProfile | null) => {
    setSelectedBrandId(profile?.id ?? null);
    setStep('generate');
  };

  const handleGenerate = async () => {
    setIsStreaming(true);
    setStreamContent('');

    // TODO: Call Tauri generate_content command
    const mockContent = `Here's your ${selectedRecipe()?.name} content:\n\nThis is a sample output that would be generated by the AI based on your source content and brand voice settings.\n\nThe actual implementation will call the Gemini API through the Rust backend.`;

    for (let i = 0; i < mockContent.length; i += 5) {
      await new Promise((r) => setTimeout(r, 20));
      setStreamContent(mockContent.slice(0, i + 5));
    }

    setIsStreaming(false);
    setStep('output');
  };

  const handleBack = () => {
    const steps: Step[] = ['input', 'recipe', 'voice', 'generate', 'output'];
    const currentIndex = steps.indexOf(step());
    if (currentIndex > 0) {
      setStep(steps[currentIndex - 1]);
    }
  };

  const handleReset = () => {
    setStep('input');
    setSelectedRecipe(null);
    setSelectedBrandId(null);
    setStreamContent('');
    setGeneratedContent(null);
  };

  return (
    <AppShell>
      <div class="space-y-6">
        {/* Progress indicator */}
        <div class="flex items-center gap-2 text-sm text-gray-500">
          <span class={step() === 'input' ? 'text-blue-600 font-medium' : ''}>Source</span>
          <span>&rarr;</span>
          <span class={step() === 'recipe' ? 'text-blue-600 font-medium' : ''}>Recipe</span>
          <span>&rarr;</span>
          <span class={step() === 'voice' ? 'text-blue-600 font-medium' : ''}>Voice</span>
          <span>&rarr;</span>
          <span
            class={step() === 'generate' || step() === 'output' ? 'text-blue-600 font-medium' : ''}
          >
            Output
          </span>
        </div>

        {/* Back button */}
        <Show when={step() !== 'input'}>
          <button
            type="button"
            class="text-gray-500 hover:text-gray-700 text-sm"
            onClick={handleBack}
          >
            &larr; Back
          </button>
        </Show>

        {/* Step content */}
        <Show when={step() === 'input'}>
          <div class="bg-white rounded-xl p-6 shadow-sm">
            <h2 class="text-xl font-semibold mb-4">Add Your Content</h2>
            <SourceInput onSubmit={handleSourceSubmit} />
          </div>
        </Show>

        <Show when={step() === 'recipe'}>
          <div class="bg-white rounded-xl p-6 shadow-sm">
            <h2 class="text-xl font-semibold mb-4">Choose Output Format</h2>
            <RecipePicker selectedId={selectedRecipe()?.id ?? null} onSelect={handleRecipeSelect} />
          </div>
        </Show>

        <Show when={step() === 'voice'}>
          <div class="bg-white rounded-xl p-6 shadow-sm">
            <h2 class="text-xl font-semibold mb-4">Apply Brand Voice</h2>
            <BrandSelector selectedId={selectedBrandId()} onSelect={handleBrandSelect} />
          </div>
        </Show>

        <Show when={step() === 'generate' || step() === 'output'}>
          <div class="bg-white rounded-xl p-6 shadow-sm">
            <StreamViewer
              isStreaming={isStreaming()}
              content={streamContent()}
              onGenerate={handleGenerate}
            />
          </div>
        </Show>

        <Show when={step() === 'output' && streamContent()}>
          <div class="bg-white rounded-xl p-6 shadow-sm">
            <OutputPreview content={generatedContent()} rawText={streamContent()} />
          </div>

          <button
            type="button"
            class="w-full py-3 bg-gray-200 rounded-lg hover:bg-gray-300"
            onClick={handleReset}
          >
            Start Over
          </button>
        </Show>
      </div>
    </AppShell>
  );
};

export default App;
